### ISSUE TITLE
FTS5 is not working with encryption on windows

### ISSUE THREAD

**Issue by 7mada123** [simolus3/sqlite3.dart#127]
`FTS5` is working fine with the default `sqlite3_flutter_libs` but when using `sqlcipher_flutter_libs` with precompiled sqlcipher `.dll` file it does not work and throw an error.

error message
```
flutter: SqliteException(1): no such module: FTS5
  Causing statement: CREATE VIRTUAL TABLE IF NOT EXISTS "table_name" USING FTS5(id, content);
```
<details>
<summary>StackTrace</summary>

```
flutter: #0      DriftCommunication.request
package:drift/…/remote/communication.dart:109
simolus3/drift#1      _RemoteQueryExecutor.ensureOpen
package:drift/…/remote/client_impl.dart:137
simolus3/drift#2      DatabaseConnectionUser.doWhenOpened
package:drift/…/api/connection_user.dart:156
simolus3/drift#3      InsertStatement.insert
package:drift/…/statements/insert.dart:73
simolus3/drift#4      provider.add
package:myapp/…/my_db/provider.dart:34
simolus3/drift#5      screen.build.<anonymous closure>
package:myapp/screen.dart:35
simolus3/drift#6      _InkResponseState.handleTap
package:flutter/…/material/ink_well.dart:1072
simolus3/drift#7      GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:253
simolus3/drift#8      TapGestureRecognizer.handleTapUp
package:flutter/…/gestures/tap.dart:627
simolus3/drift#9      BaseTapGestureRecognizer._checkUp
package:flutter/…/gestures/tap.dart:306
simolus3/drift#10     BaseTapGestureRecognizer.handlePrimaryPointer
package:flutter/…/gestures/tap.dart:239
simolus3/drift#11     PrimaryPointerGestureRecognizer.handleEvent
package:flutter/…/gestures/recognizer.dart:615
simolus3/drift#12     PointerRouter._dispatch
package:flutter/…/gestures/pointer_router.dart:98
simolus3/drift#13     PointerRouter._dispatchEventToRoutes.<anonymous closure>
package:flutter/…/gestures/pointer_router.dart:143
simolus3/drift#14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617:13)
simolus3/drift#15     PointerRouter._dispatchEventToRoutes
package:flutter/…/gestures/pointer_router.dart:141
simolus3/drift#16     PointerRouter.route
package:flutter/…/gestures/pointer_router.dart:127
simolus3/drift#17     GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart:460
simolus3/drift#18     GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:440
simolus3/drift#19     RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:337
simolus3/drift#20     GestureBinding._handlePointerEventImmediately
package:flutter/…/gestures/binding.dart:395
simolus3/drift#21     GestureBinding.handlePointerEvent
package:flutter/…/gestures/binding.dart:357
simolus3/drift#22     GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart:314
simolus3/drift#23     GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:295
simolus3/drift#24     _invoke1 (dart:ui/hooks.dart:167:13)
simolus3/drift#25     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:341:7)
simolus3/drift#26     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
```
</details>

note:
Encryptions works fine without adding FTS5 and I am facing this issue only on windows.

**Comment by simolus3** [comment]
I've never tested the availability of fts5 in `sqlcipher_flutter_libs`, I'll look into that. Out of interest, on which platform did encrypted fts5 work at all?

**Comment by 7mada123** [comment]
Hi @simolus3
It works on Android, IOS and MacOS out of the box.
I haven't test it on Linux yet

**Comment by 7mada123** [comment]
This issue is related to the compiled lib, the package works perfectly fine (both sqlite and drift).
