### ISSUE TITLE
Writing Tests using sqlite3 package in a pure dart package

### ISSUE THREAD

**Issue by Leylan24** [simolus3/sqlite3.dart#188]
When running tests in a pure sqllite package I get the following error:

```
Testing started at 22:37 ...
Using sqlite3 Version(libVersion: 3.43.1, sourceId: 2023-09-11 12:01:27 2d3a40c05c49e1a49264912b1a05bc2143ac0e7c3df588276ce80a4cbc9bd1b0, number: 3043001)
Unhandled exception:
PathAccessException: Deletion failed, path = 'C:\Users\leyla\AppData\Local\Temp\dart_test.kernel.54076555' (OS Error: The process cannot access the file because it is being used by another process.
, errno = 32)
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _Directory._delete.<anonymous closure> (dart:io/directory_impl.dart:185:7)
<asynchronous suspension>
#2      RetryDelete.deleteWithRetry (package:test_core/src/util/io.dart:236:9)
<asynchronous suspension>
#3      _TestCompilerForLanguageVersion.dispose.<anonymous closure> (package:test_core/src/runner/vm/test_compiler.dart:198:11)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
<asynchronous suspension>
#5      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
<asynchronous suspension>
#6      Loader.close.<anonymous closure>.<anonymous closure> (package:test_core/src/runner/loader.dart:295:13)
<asynchronous suspension>
#7      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
<asynchronous suspension>
#8      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
<asynchronous suspension>
#9      Loader.close.<anonymous closure> (package:test_core/src/runner/loader.dart:292:9)
<asynchronous suspension>
#10     Runner.close.<anonymous closure> (package:test_core/src/runner.dart:249:9)
<asynchronous suspension>
#11     _execute (package:test_core/src/executable.dart:171:5)
<asynchronous suspension>
#12     main (package:test_core/src/executable.dart:38:3)
<asynchronous suspension>
#13     main (package:test/src/executable.dart:27:3)
<asynchronous suspension>

Process finished with exit code 255

```
it does pick up the sqlite version correctly however when executing it just fails:

`Using sqlite3 Version(libVersion: 3.43.1, sourceId: 2023-09-11 12:01:27 `

**Comment by Leylan24** [comment]
was an error on my side
