### ISSUE TITLE
Invalid argument(s): Failed to load dynamic library 'sqlite3.dll': The specified module could not be found

### ISSUE THREAD

**Issue by loveishere** [simolus3/sqlite3.dart#216]
```
Unhandled exception:
Invalid argument(s): Failed to load dynamic library 'sqlite3.dll': The specified module could not be found.
 (error code: 126)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
#2      _defaultOpen (package:sqlite3/src/ffi/load_library.dart:81:27)
#3      OpenDynamicLibrary.openSqlite (package:sqlite3/src/ffi/load_library.dart:127:12)
#4      sqlite3 (package:sqlite3/src/ffi/api.dart:13:39)
#5      _openConnection.<anonymous closure> (package:hc_base/common/todoitems.dart:54:5)
#6      new Future.sync (dart:async/future.dart:305:31)
#7      LazyDatabase._awaitOpened (package:drift/src/utils/lazy_database.dart:47:14)
#8      LazyDatabase.ensureOpen (package:drift/src/utils/lazy_database.dart:61:12)
#9      DatabaseConnectionUser.doWhenOpened (package:drift/src/runtime/api/connection_user.dart:162:21)
#10     RunWithEngine.withCurrentExecutor (package:drift/src/runtime/api/connection_user.dart:621:19)
#11     SimpleSelectStatement._getRaw (package:drift/src/runtime/query_builder/statements/select/select.dart:80:21)
#12     SimpleSelectStatement.get (package:drift/src/runtime/query_builder/statements/select/select.dart:64:12)
#13     AppDatabase.Order (package:hc_base/common/todoitems.dart:29:57)
#14     main (package:hc_base/common/main.dart:30:20)
#15     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#16     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by simolus3** [comment]
On this OS is this? Is this in a Flutter app? Did you add a dependency on `sqlite3_flutter_libs`?

**Comment by Ferrikkuso** [comment]
I have the same problem. 

I'm trying to run the example code for sqlite3 on Windows. I'm working on a dart project. I tried adding the file "sqlite3.dll" to my sysem environment path but the problem persists. 

I get this error message:

nvalid argument(s): Failed to load dynamic library 'sqlite3.dll': error code 126
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
#2      _defaultOpen (package:sqlite3/src/ffi/load_library.dart:81:27)
#3      OpenDynamicLibrary.openSqlite (package:sqlite3/src/ffi/load_library.dart:127:12)
#4      sqlite3 (package:sqlite3/src/ffi/api.dart:13:39)
#5      main (file:///C:/Dev/MATA/fridgelogic/bin/dBCreator.dart:22:23)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
