### ISSUE TITLE
Issue with auto increment

### ISSUE THREAD

**Issue by wayne-li2** [simolus3/sqlite3.dart#3]
**Using**: pure Dart sqlite
**Version**: 0.1.4
**Reproducible example**:
```
import 'package:sqlite3/sqlite3.dart';

main() {
  final db = sqlite3.openInMemory();

  // Create a table.
  String createTableStatement = '''
    CREATE TABLE users (
      user_id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
      username TEXT NOT NULL,
      email TEXT NOT NULL
    );
  ''';
  db.execute(createTableStatement);

  //INSERT INTO table_name (column1, column2, column3, ...)
  //VALUES (value1, value2, value3, ...);

  // Insert a user.
  String insertRowStatement = '''
    INSERT INTO users (username, email)
    VALUES ("Wayne", "My Email");
  ''';
  db.execute(insertRowStatement);
}
```
**What should happen**: Successfully insert into database, as auto increment should automatically create user_id=1.
**What happens**:
```
Unhandled exception:
SqliteException(1299): NOT NULL constraint failed: users.user_id
#0      DatabaseImpl.execute (package:sqlite3/src/impl/database.dart:93:7)
#1      main (package:local_api/src/db/db.dart:24:6)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by wayne-li2** [comment]
I realize this is a lightweight wrapper around sqlite, but if my memory serves correctly, this works with other sqlite libraries on other languages. Let me know if this is out of place, and I will close it.

**Comment by wayne-li2** [comment]
I am dumb -- it does not work with plain sqlite either... I must have misremembered

**Comment by wayne-li2** [comment]
Yep, I used BIGINT instead of INTEGER PRIMARY KEY. Embarrassing :D sorry for the extra issue
