### ISSUE TITLE
Invalid argument(s): Failed to load dynamic library 'sqlite3.dll': error code 1427108184

### ISSUE THREAD

**Issue by 906499861** [simolus3/sqlite3.dart#78]
`Unhandled exception:
Invalid argument(s): Failed to load dynamic library 'sqlite3.dll': error code 1427108184
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
#2      _defaultOpen (package:sqlite3/src/load_library.dart:76:27)
#3      OpenDynamicLibrary.openSqlite (package:sqlite3/src/load_library.dart:122:12)
#4      sqlite3 (package:sqlite3/src/api/sqlite3.dart:10:38)
#5      main (file:///I:/Flutter/flutterproject/sqlite3_test/bin/sqlite3_test.dart:6:26)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)`
<hr><br>
![QQ截图20220215170104](https://user-images.githubusercontent.com/82579833/154028514-841da9fd-1b09-4634-97f2-6df34a0ebc36.png)

![QQ截图20220215170355](https://user-images.githubusercontent.com/82579833/154028522-73ee3774-9ac0-4c74-9f67-248b48bfda0b.png)

**Comment by simolus3** [comment]
On which Android version / device is this happening?

**Comment by 906499861** [comment]
> On which Android version / device is this happening?
The dart project I created, windows

**Comment by 906499861** [comment]
> On which Android version / device is this happening?
![QQ截图20220215193451](https://user-images.githubusercontent.com/82579833/154054419-9c2e47f2-287b-4ac6-b99a-230393512b68.png)

**Comment by simolus3** [comment]
Oh right, of course. Under Windows you'll need to provide your own `sqlite3.dll` and ship it with your app as described in the [README](https://github.com/simolus3/sqlite3.dart/tree/master/sqlite3#supported-platforms).

**Comment by 906499861** [comment]
> 哦，对，当然。在 Windows 下，您需要提供您自己的`sqlite3.dll`并将其与您的应用程序一起提供，如[README](https://github.com/simolus3/sqlite3.dart/tree/master/sqlite3?rgh-link-date=2022-02-15T11%3A44%3A45Z#supported-platforms)中所述。

除了windows是不是其他设备不用提供。
